remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
title: "Actors Representation: Actor’s Recognition, Gender and Ethnicity throughout history and time"
description: Explore the exciting life of Actors!
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
